In [43]:
import pandas as pd
import numpy as np
data=pd.read_csv(r"C:\Users\ankit\OneDrive\Desktop\Company_Employee_Pandas_Practice.csv")
data.head(5)

,Employee_ID,Name,Age,Gender,City,Department,Job_Role,Education,Experience_Years,Employment_Type,Salary,Bonus,Performance_Rating,Projects_Completed,Working_Hours,Joining_Date,Status,Email
0,10001,Rahul Gupta,55.0,Female,Kolkata,Marketing,Accountant,B.Com,24.2,Contract,101693.0,28617,Needs Improvement,5,42.6,2017-03-11,Resigned,employee10001@company.com
1,10002,Nisha Joshi,49.0,Female,Gurugram,Marketing,Intern,BCA,17.4,Contract,60135.0,9192,Needs Improvement,19,47.4,2018-05-31,Resigned,employee10002@company.com
2,10003,Nisha Kumar,35.0,Female,Kolkata,Data Analytics,Analyst,BBA,2.1,Intern,52862.0,12745,Needs Improvement,19,44.7,2022-06-30,Active,employee10003@company.com
3,10004,Rahul Yadav,53.0,Female,Delhi,Finance,Sales Executive,B.Com,21.6,Contract,161262.0,32020,Excellent,15,50.8,2024-07-27,Resigned,employee10004@company.com
4,10005,Sneha Patel,27.0,Male,Jaipur,Finance,HR Executive,MBA,12.0,Intern,95199.0,44678,Excellent,1,31.8,2023-12-02,Resigned,employee10005@company.com

In [44]:
data.columns

Index(['Employee_ID', 'Name', 'Age', 'Gender', 'City', 'Department',
       'Job_Role', 'Education', 'Experience_Years', 'Employment_Type',
       'Salary', 'Bonus', 'Performance_Rating', 'Projects_Completed',
       'Working_Hours', 'Joining_Date', 'Status', 'Email'],
      dtype='str')

In [45]:
data.isnull().sum()

Employee_ID            0
Name                   0
Age                   20
Gender                 0
City                  15
Department             0
Job_Role               0
Education             15
Experience_Years       0
Employment_Type        0
Salary                20
Bonus                  0
Performance_Rating    10
Projects_Completed     0
Working_Hours          0
Joining_Date           0
Status                 0
Email                  0
dtype: int64

In [46]:
# Handeling the missing Data 
data["Age"]=data["Age"].fillna(data["Age"].mean())
data["City"]=data["City"].fillna("Uknown")
data["Education"]=data["Education"].fillna("Unknown degree")
data["Salary"]=data["Salary"].fillna(data["Salary"].median())
data["Performance_Rating"]=data["Performance_Rating"].fillna("Uknown")

In [47]:
# Handel The Inconsistent Values
data["Name"]=data["Name"].str.strip().str.lower()

In [48]:
data.columns

Index(['Employee_ID', 'Name', 'Age', 'Gender', 'City', 'Department',
       'Job_Role', 'Education', 'Experience_Years', 'Employment_Type',
       'Salary', 'Bonus', 'Performance_Rating', 'Projects_Completed',
       'Working_Hours', 'Joining_Date', 'Status', 'Email'],
      dtype='str')

In [49]:
data["Gender"]=data["Gender"].str.strip().str.lower()
data["City"]=data["City"].str.strip().str.lower()
data["Department"]=data["Department"].str.strip().str.upper()
data["Job_Role"]=data["Job_Role"].str.strip().str.capitalize()
data["Education"]=data["Education"].str.strip().str.capitalize()
data["Status"]=data["Status"].str.strip().str.capitalize()

In [50]:
data

,Employee_ID,Name,Age,Gender,City,Department,Job_Role,Education,Experience_Years,Employment_Type,Salary,Bonus,Performance_Rating,Projects_Completed,Working_Hours,Joining_Date,Status,Email
0,10001,rahul gupta,55.0,female,kolkata,MARKETING,Accountant,B.com,24.2,Contract,101693.0,28617,Needs Improvement,5,42.6,2017-03-11,Resigned,employee10001@company.com
1,10002,nisha joshi,49.0,female,gurugram,MARKETING,Intern,Bca,17.4,Contract,60135.0,9192,Needs Improvement,19,47.4,2018-05-31,Resigned,employee10002@company.com
2,10003,nisha kumar,35.0,female,kolkata,DATA ANALYTICS,Analyst,Bba,2.1,Intern,52862.0,12745,Needs Improvement,19,44.7,2022-06-30,Active,employee10003@company.com
3,10004,rahul yadav,53.0,female,delhi,FINANCE,Sales executive,B.com,21.6,Contract,161262.0,32020,Excellent,15,50.8,2024-07-27,Resigned,employee10004@company.com
4,10005,sneha patel,27.0,male,jaipur,FINANCE,Hr executive,Mba,12.0,Intern,95199.0,44678,Excellent,1,31.8,2023-12-02,Resigned,employee10005@company.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000,10011,pooja mehta,40.0,male,pune,SALES,Intern,Bca,20.7,Contract,28262.0,40910,Excellent,11,52.3,2017-10-08,Active,employee10011@company.com
1001,10026,karan kumar,59.0,male,pune,MARKETING,Accountant,Mba,4.2,Part-Time,118135.0,45151,Needs Improvement,12,33.6,2019-10-22,On leave,employee10026@company.com
1002,10051,ankit joshi,59.0,male,noida,MARKETING,Designer,M.tech,0.3,Full-Time,148662.0,27574,Excellent,12,42.3,2022-11-27,Active,employee10051@company.com
1003,10076,nisha gupta,21.0,female,noida,OPERATIONS,Hr executive,Bca,2.1,Part-Time,119154.0,9632,Average,9,32.6,2019-12-14,Active,employee10076@company.com
1004,10101,aditya sharma,26.0,male,chennai,MARKETING,Data scientist,Mca,24.9,Intern,112948.0,45054,Excellent,2,34.9,2020-05-07,On leave,employee10101@company.com

In [51]:
# Checking Duplicate Values
data.duplicated().sum()

np.int64(5)

In [52]:
data.duplicated().sum()

np.int64(5)

In [53]:
data=data.drop_duplicates()

In [54]:
data.duplicated().sum()

np.int64(0)

In [ ]:
data["Age"]=data["Age"].astype("int64")

In [59]:
data["Age"].unique()

array([55, 49, 35, 53, 27, 32, 50, 41, 51, 44, 40, 57, 24, 48, 52, 56, 54,
       22, 26, 59, 23, 38, 60, 46, 28, 43, 34, 25, 58, 45, 37, 21, 31, 30,
       36, 29, 42, 47, 39, 33])